### ISSUE TITLE
Determine contract_address from wasm bytes.

### ISSUE THREAD

**Issue by bostontrader** [polkascan/py-substrate-interface#116]
Hello folks,

Is there a way to determine the contract_address of a contract given the initial metadata and wasm files?

The ability to do this would solve a nettlesome issue that I, as well as anybody else dealing with these contracts, encounter.

When I initially create_from_contract_files and then deploy a contract, I receive a contract_address in the results.

But I then have to record this somehow so that I can find it again in subsequent invocations of my program.  I can think of several ways to do this.  Perhaps I could build a dict mapping the wasm bytes to a contract_address and serialize/deserialize/read/write/to/from an external file. But this is a cumbersome nuisance and it makes me feel dirty.  I can't help but think there's a better way to do this.

Any advice vastly appreciated. Thanks.

**Comment by arjanz** [comment]
I'm not sure how exactly the contract address is being generated in Substrate, but I also noticed it was deterministic (when leaving the `deployment_salt` empty that is). I think the best way is to inspect the contract pallet in the Substrate sourcecode. 

However, I wouldn't recommend to do this assumption, because - especially now still in pre-production phase - functionality tend to change over time and could be this is not the case anymore in the future. The contract address is being returned in the `Instantiated` event after invoking the `Contracts.instantiate` call and even if that is changing, we would update the contracts interface classes so it would be agnostic of future changes.

**Comment by bostontrader** [comment]
My use case for this capacity is that I run a fresh node and then an integration test that will populate it with some contracts.  Later, I re-run the test.  I don't want to redeploy the contracts, I just want to find their existing contract addresses.  However, considering that there's no apparent easy answer to this, I suppose I should just stick with best practices and just brainwipe everything, chain and all, with each invocation of my test.

In real use, people will just copy -n- paste these addresses and save them on their own for later use.

Thanks for the insight and I think this is case-closed.

**Comment by arjanz** [comment]
Maybe you can try:

```python
contracts = substrate.query_map("Contracts", "ContractInfoOf")

for contract_address, contract_info in contracts:
    print(contract_address, contract_info.value)
```
This will query all existing contracts known in storage (retrieving all storage entries with `query_map` will work for all mapped storage functions) Maybe this is what you need
