### ISSUE TITLE
Sudden error when accessing ANY method via py substrate interface

### ISSUE THREAD

**Issue by DanielMS93** [polkascan/py-substrate-interface#340]
I have encountered an issue recently when trying to access any method. 

Specifically, I am using the acala network via:

```
        acala_substrate = SubstrateInterface(
            url="wss://acala-rpc-1.aca-api.network",
            ss58_format=10,
            type_registry_preset="acala",
        )
```

<img width="915" alt="image" src="https://github.com/polkascan/py-substrate-interface/assets/44974943/0c3a2319-b88c-4cca-ae71-8be8431b196e">

Another method call example:

<img width="875" alt="image" src="https://github.com/polkascan/py-substrate-interface/assets/44974943/1c4dfe84-330f-445a-a9b7-210218e5e9ad">

Any ideas why, this has totally broken my application and i am unclear what has changed...

**Comment by DanielMS93** [comment]
Update: I was able to access the get_block() method when installing fresh on my local - will try updating the package on my VM

**Comment by arjanz** [comment]
I saw the exception raised in `get_chain_head()`, which could be related to a [recent change](https://github.com/polkascan/py-substrate-interface/blob/5b56f1cead90f030170c2ec0d8f7fdf910379b2b/substrateinterface/base.py#L434)  to determine supported RPC methods. Newer Substrate RPC dropped some older RPC aliases. 

This change is available since [v1.6.1](https://github.com/polkascan/py-substrate-interface/releases/tag/v1.6.1) release, maybe you had the library pinned to an older version and there was a Substrate upgrade recently?

**Comment by arjanz** [comment]
@DanielMS93 Are you still experiencing this issue?

**Comment by DanielMS93** [comment]
Thanks for getting back @arjanz! i upgraded my version to latest and all issues were resolved! apologies for not updating this thread!
