### ISSUE TITLE
substrate websocket getting blocked at subscription_handler

### ISSUE THREAD

**Issue by Jessie-1** [polkascan/py-substrate-interface#352]
unable to subscribe more due to blocking.

**Comment by arjanz** [comment]
The library is intended for a sync environment, but if you aim to subscribe to multiple storage keys at once you can have a look at the `subscribe_storage()` function, see docs:

https://polkascan.github.io/py-substrate-interface/usage/subscriptions/#subscribe-to-multiple-storage-keys

Otherwise you can resort to work with threads, be sure to use a separate instance of `SubstrateInterface` per thread because otherwise it wouldn't be threadsafe. See examples mentioned in:

https://github.com/polkascan/py-substrate-interface/issues/206#issue-1188620072

https://github.com/polkascan/py-substrate-interface/issues/82#issuecomment-810957617
