### ISSUE TITLE
ContractExecutionReceipt.process_events() crashes on events from other contracts.

### ISSUE THREAD

**Issue by h4nsu** [polkascan/py-substrate-interface#379]
As far as I understand the underlying code, it seems like `ContractExecutionReceipt.process_events()` 
filters all the events of type `ContractEmitted` and attempts to decode them using contract's metadata. However, if "our" contract call resulted in some cross-contract calling and "their" contracts emitted their events, we won't be able to decode them (we have only "our" metadata, not theirs). Currently this results in unhandled `scalecodec` exception and a crash. Maybe it's a good idea to put this part in a try-catch block?

**Comment by DamianStraszak** [comment]
I think even better would be to inspect the `contract` field of the `ContractEmitted` event and decode only ours. Inspect the definition of `ContractEmitted` variant below. We don't even want to attempt decoding events from other contracts, because we could succeed by coincidence and return some incorrect event as a result.

![image](https://github.com/polkascan/py-substrate-interface/assets/23038619/475e7217-bfb2-4dee-b40d-1460480fc3b9)

**Comment by h4nsu** [comment]
@DamianStraszak Good idea, I drafted a PR with the fix you described

**Comment by arjanz** [comment]
> I think even better would be to inspect the `contract` field of the `ContractEmitted` event and decode only ours. Inspect the definition of `ContractEmitted` variant below. We don't even want to attempt decoding events from other contracts, because we could succeed by coincidence and return some incorrect event as a result.
> 

@DamianStraszak I agree, currently it has the false assumption all `ContractEmitted` events in a block are related to one specific contract, which is of course not true. Checking if the events are emitted from that specific contract would be a good fix.

@h4nsu I'll take a look at the PR

**Comment by arjanz** [comment]
PR released: https://github.com/polkascan/py-substrate-interface/releases/tag/v1.7.7

**Comment by h4nsu** [comment]
Thanks!
