### ISSUE TITLE
Runtime update not handled

### ISSUE THREAD

**Issue by pavelrib** [polkascan/py-substrate-interface#48]
There was a runtime update on Polkadot which is causing block parsing to fail. First failed on block 2436698.
Stacktrace:
```
block_data = self._client.get_runtime_block(block_hash=block_hash)
  File "/app_dir/env/lib/python3.7/site-packages/substrateinterface/__init__.py", line 1739, in get_runtime_block
    extrinsic_decoder.decode()
  File "/app_dir/env/lib/python3.7/site-packages/scalecodec/base.py", line 280, in decode
    self.value = self.process()
  File "/app_dir/env/lib/python3.7/site-packages/scalecodec/block.py", line 158, in process
    self.call = self.metadata.call_index[self.call_index][1]
KeyError: '0a00'
``` 
Are there any plans to support such network upgrades in some automatic process?

**Comment by arjanz** [comment]
The library should already handle runtime upgrades automatically because metadata is retrieved on chain and type definition changes are also managed in the libary (e.g. https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/polkadot.json#L92), but it seems you addressed a corner case where the metadata of the wrong runtime is used to decode the extrinsics in that block. 

Block number 2436698 is the block where the runtime upgrade takes place (https://polkascan.io/polkadot/block/2436698#events) and the end result is the _new_ runtime, but the calls in this block however should still processed against the _old_ runtime. This is a bug in the library, thank for reporting!

**Comment by arjanz** [comment]
Pushed release with fix to PyPI
