### ISSUE TITLE
Outdated examples at pkg.go.dev

### ISSUE THREAD

**Issue by ChinmayPatel** [polkascan/py-substrate-interface#58]
I just tried the examples (simpleTransfer example in particular) at https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client#pkg-examples and ran into a bunch of compatibility issue. 

Eventually, I got it working using the `main_test.go` file and the answer at https://github.com/centrifuge/go-substrate-rpc-client/issues/99 . 

Can someone update the docs on the pkg.go.dev site? I'm new to go and not sure how to do it. If you can point me in the right direction, I can update the examples myself.

**Comment by arjanz** [comment]
Hi, I think you accidentally posted this issue in the wrong repos, this is the Python implementation.. :) 

Nevertheless I briefly checked the issue you were refererring to and I also came across these kind of Substrate errors when the format of the `Address` SCALE-type was incorrect. 

For example on some Substrate chains it's a simpler `AccountId` format, others have the `Address` format (which include an extra byte to determine if it's signed by an `AcccountId` or `AccountIndex` so that would basically derail the SCALE decoding. Long shot but maybe that can give a clue what problem you are facing.

**Comment by ChinmayPatel** [comment]
That is so stupid of me :P Thanks for correcting.

The problem was with Pallet indices and how it is interpreted differently in Substrate core repo and on Polkadot. It's resolved, but thanks for your answer :)

I'll close the issue and will post the problem at the right place. Hopefully, it unblocks others.

Thanks again!
