### ISSUE TITLE
Unsupported Hash Type

### ISSUE THREAD

**Issue by unconst** [polkascan/py-substrate-interface#76]
The interface does not implement the identity hasher type for things like u64

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/substrateinterface/base.py in iterate_map(self, module, storage_function, block_hash)
   1116                                     concat_hash_len = 16
   1117                                 else:
-> 1118                                     raise ValueError('Unsupported hash type')
   1119                             else:
   1120                                 raise ValueError('Given storage is not a map')

ValueError: Unsupported hash type 

We hacked this to work for our code using the following trick:

                               if storage_item.type['MapType']['hasher'] == "Blake2_128Concat":
                                    concat_hash_len = 32
                                elif storage_item.type['MapType']['hasher'] == "Twox64Concat":
                                    concat_hash_len = 16
                                elif storage_item.type['MapType']['hasher'] == "Identity":
                                    concat_hash_len = 0

**Comment by arjanz** [comment]
Thanks for pointing this out, for the Identity hasher indeed the whole key is used with no prefix. 

I also saw the `state_getPairs` is an unsafe RPC method, which is for example blocked by the public available nodes (because of possible performance drain). I will put a new function `query_map` on the todolist that will combine `state_getKeysPaged` `state_queryStorageAt` and will return a nested list of `ScaleType` objects.

**Comment by arjanz** [comment]
Check out the latest release, it has an improved `query_map` function that also works on the public nodes:

https://github.com/polkascan/py-substrate-interface/blob/586f7f921d61493d3f5f489a4f0e0d11beb71b12/substrateinterface/base.py#L1148
