### ISSUE TITLE
'None' Author

### ISSUE THREAD

**Issue by migueldingli1997** [polkascan/py-substrate-interface#77]
I'm getting a 'None' response when querying the Author for a particular block:
```
author = API.query(
  module='Authorship',
  storage_function='Author',
  params=[],
  block_hash='0x2a24f495db02cdf58bdc6a8fecea38f7e56b02b99822b33436d4aeb535c0b917'
)
```

**Comment by arjanz** [comment]
Are you trying the retrieve the block author? Because this is not where the storage function you mentioned is for, so a `None` in this case is the expected result. (you can reference https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/chainstate for this)

Nevertheless I agree a convenience function for determining the block author could be useful, this information in encapsulated in the log digest header.

For Polkascan I wrote the following snippet to point you in the right direction,  I will also put on the todo list for the library:

```python
if log.data['value']['engine'] == 'BABE':
    # Determine block producer
    babe_predigest_cls = RuntimeConfiguration().get_decoder_class('RawBabePreDigest')

    babe_predigest = babe_predigest_cls(
        ScaleBytes(bytearray.fromhex(log.data['value']['data'].replace('0x', '')))
    ).decode()

    if len(list(babe_predigest.values())) > 0:

        babe_predigest_value = list(babe_predigest.values())[0]

        log.data['value']['data'] = babe_predigest_value
        self.block.authority_index = log.data['value']['data']['authorityIndex']
        self.block.slot_number = log.data['value']['data']['slotNumber']

```

**Comment by migueldingli1997** [comment]
Thank you for the prompt reply! Yes I was trying to get the block author. I got the Author/Authorship values by calling the API's `get_metadata_storage_functions` function, which I assume lists the storage functions available at the particular block. Sounds like I was not completely on track hehe. Thank you for the chain state link, I did not know about that!
