### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by afeezaziz** [polkascan/py-substrate-interface#80]
When I am running using simple Python script I am getting this error:

`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate` when connecting to a wss:// but this has no problem when using polkadot.js

**Comment by arjanz** [comment]
Do you have an endpoint for me to test?

**Comment by afeezaziz** [comment]
You mean for the substrate websocket URL or for the API wrapper I am building?

The substrate websocket URL is `wss://1.dcb.my`

**Comment by arjanz** [comment]
There seems to be an issue with the validation of the certificate of you endpoint, I quickly Googled, have you tried this: https://moreless.medium.com/how-to-fix-python-ssl-certificate-verify-failed-97772d9dd14c

**Comment by afeezaziz** [comment]
Yes, I tried both solutions as suggested by the write-up but both failed.

FYI, the certificate is purchased from Comodo and access through polkadot.js is fine.

**Comment by garrettmaring** [comment]
@arjanz those fixes didn't work for me though i'd like to set up the correct way to use SSL with py-substrate-interface locally

**Comment by arjanz** [comment]
The library uses https://pypi.org/project/websocket-client/ as library to connect to websockets, so things are a bit out of our control, but after some more searching online I found that in some cases the problem is caused by a missing intermediate CA certificate:

https://stackoverflow.com/a/52097983/269465

https://www.py4u.net/discuss/214056

What I can do is provide a way to pass options to the `create_connection()` of websocket-client, so you can provide this context and see if that solves the problem for you. This will be available as `ws_options` in the constructor.

Something like:

```python
import ssl
from substrateinterface import SubstrateInterface

sslopt={"cert_reqs": ssl.CERT_NONE}

   substrate = SubstrateInterface(
    url="wss://URL",
    ws_options={'sslopt': sslopt}
)
