### ISSUE TITLE
Unending QueryMapResult iterator

### ISSUE THREAD

**Issue by apuigsech** [polkascan/py-substrate-interface#95]
The following code is never ending because the iterator is not raising 'StopIteration'. It its iterating over the same data over and over again:

```
ledger_map = self.query_map(
    module='Staking',
    storage_function='Ledger',
)

ledger = {} 
for k,v in ledger_map:
   ledger[k] = v
```

I think this happens when the content exceeds the page, so the iterator is retrieving more data here:

```
    def retrieve_next_page(self, start_key) -> list:
        if not self.substrate:
            return []

        result = self.substrate.query_map(module=self.module, storage_function=self.storage_function,
                                          page_size=self.page_size, block_hash=self.block_hash, start_key=start_key,
                                          max_results=self.max_results)
        return result.records

    (...)

        if self.current_index >= len(self.records):
            # try to retrieve next page from node
            self.records += self.retrieve_next_page(start_key=self.last_key)
```

**Comment by arjanz** [comment]
The issue was the `start_key` of the next page wasn't updated correctly, so the same results were retrieved over and over again.. The Substrate node only allows a maximum amount of storage keys per request, so it has to paginated with a `page_size` and `start_key`, which I automated by exposing this mechanism through an iterator.

**Comment by arjanz** [comment]
https://github.com/polkascan/py-substrate-interface/releases/tag/v0.12.5
